services:
  - type: web
    name: health-assistant
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir /opt/render/project app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
